In [18]:
import polars as pl
import numpy as np
team12Stats = pl.read_csv('../finalData/team12Stats.csv')
balltoball = pl.read_csv('../finalData/balltoball.csv')
playerStats = np.load('../finalData/playerStats.npy', allow_pickle=True)
team12Stats

shape: (3_399, 24)
┌──────────┬────────┬─────┬─────┬───┬──────────┬──────────┬──────────────┬──────────────┐
│ match_id ┆ gender ┆ Mat ┆ Won ┆ … ┆ HS_team2 ┆ LS_team2 ┆ AveRPW_team2 ┆ AveRPO_team2 │
│ ---      ┆ ---    ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---          ┆ ---          │
│ i64      ┆ i64    ┆ i64 ┆ i64 ┆   ┆ i64      ┆ f64      ┆ f64          ┆ f64          │
╞══════════╪════════╪═════╪═════╪═══╪══════════╪══════════╪══════════════╪══════════════╡
│ 1298172  ┆ 1      ┆ 9   ┆ 5   ┆ … ┆ 166      ┆ 112.0    ┆ 21.33        ┆ 6.97         │
│ 1145983  ┆ 1      ┆ 6   ┆ 2   ┆ … ┆ 167      ┆ 0.0      ┆ 23.24        ┆ 7.92         │
│ 1197142  ┆ 1      ┆ 4   ┆ 3   ┆ … ┆ 197      ┆ 0.0      ┆ 25.15        ┆ 8.17         │
│ 1197145  ┆ 1      ┆ 4   ┆ 3   ┆ … ┆ 197      ┆ 0.0      ┆ 25.15        ┆ 8.17         │
│ 1299832  ┆ 1      ┆ 13  ┆ 3   ┆ … ┆ 190      ┆ 94.0     ┆ 23.33        ┆ 7.24         │
│ …        ┆ …      ┆ …   ┆ …   ┆ … ┆ …        ┆ …        ┆ …            ┆ …            │
│ 682917   ┆ 1      ┆ 3   ┆ 0   ┆ … ┆ 163      ┆ 0.0      ┆ 28.46        ┆ 7.95         │
│ 1298142  ┆ 1      ┆ 8   ┆ 3   ┆ … ┆ 174      ┆ 115.0    ┆ 16.94        ┆ 7.13         │
│ 439139   ┆ 1      ┆ 3   ┆ 0   ┆ … ┆ 105      ┆ 105.0    ┆ 10.5         ┆ 5.29         │
│ 593986   ┆ 1      ┆ 11  ┆ 7   ┆ … ┆ 130      ┆ 100.0    ┆ 13.75        ┆ 5.67         │
│ 593987   ┆ 1      ┆ 11  ┆ 7   ┆ … ┆ 130      ┆ 100.0    ┆ 13.75        ┆ 5.67         │
└──────────┴────────┴─────┴─────┴───┴──────────┴──────────┴──────────────┴──────────────┘

In [15]:
team12Stats = team12Stats.sort("match_id")
balltoball = balltoball.sort("match_id")
playerStats = playerStats[playerStats[:, 0].argsort()]
playerStats

array([[[[1.03143300e+06, 4.00000000e+00, 4.00000000e+00, ...,
          3.00000000e+00, 0.00000000e+00, 1.30434783e-01],
         [1.03143300e+06, 3.00000000e+00, 2.00000000e+00, ...,
          8.00000000e+00, 1.00000000e+00, 6.92307692e-01],
         [1.03143300e+06, 3.00000000e+00, 3.00000000e+00, ...,
          2.30000000e+01, 0.00000000e+00, 1.00000000e+00],
         ...,
         [1.03143300e+06, 2.00000000e+00, 2.00000000e+00, ...,
          5.00000000e+00, 0.00000000e+00, 1.21951220e-01],
         [1.03143300e+06, 2.00000000e+00, 1.00000000e+00, ...,
          1.00000000e+00, 0.00000000e+00, 2.50000000e-01],
         [1.03143300e+06, 2.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00]],

        [[1.03482700e+06, 3.00000000e+00, 3.00000000e+00, ...,
          2.00000000e+00, 0.00000000e+00, 1.05263158e-01],
         [1.03482700e+06, 3.00000000e+00, 3.00000000e+00, ...,
          6.00000000e+00, 1.00000000e+00, 7.00000000e-01],
        

In [26]:
playerStats[:, 0][0]

array([1.00134900e+06, 3.00000000e+00, 3.00000000e+00, 1.08000000e+02,
       1.42100000e+02, 3.60000000e+01, 3.59300000e+01, 1.08200000e+03,
       3.10000000e+01, 1.46680000e+02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 2.00000000e+00, 0.00000000e+00,
       2.70000000e+01, 2.00000000e+00, 1.35000000e+01, 8.00000000e+00,
       8.00000000e+00, 0.00000000e+00, 2.58064516e-01])

In [16]:
len(np.unique(playerStats[:, 0, 0]))

45

In [3]:
# Extract match_id columns from each dataset
team12_match_ids = team12Stats.select('match_id').unique()  # Polars unique match_ids in team12Stats
balltoball_match_ids = balltoball.select('match_id').unique()  # Polars unique match_ids in balltoball

# Extract match_ids from playerStats (assuming match_id is in the first column)
player_match_ids = np.unique(playerStats[:, 0, 0])

# Convert Polars Series to Numpy for intersection
team12_match_ids_np = team12_match_ids.to_numpy().flatten()
balltoball_match_ids_np = balltoball_match_ids.to_numpy().flatten()

# Find intersection of match_id across all three datasets
common_match_ids = np.intersect1d(np.intersect1d(team12_match_ids_np, balltoball_match_ids_np), player_match_ids)

print("Common match IDs across all datasets:", common_match_ids)

Common match IDs across all datasets: [ 211028.  211048.  225263. ... 1450753. 1450759. 1450765.]


In [4]:
# Filter team12Stats
filtered_team12Stats = team12Stats.filter(pl.col('match_id').is_in(common_match_ids))

# Filter balltoball
filtered_balltoball = balltoball.filter(pl.col('match_id').is_in(common_match_ids))

# Filter playerStats (assuming match_id is the first column)
filtered_playerStats = playerStats[np.isin(playerStats[:, 0, 0], common_match_ids)]

In [5]:
filtered_playerStats.shape, filtered_team12Stats.shape, filtered_balltoball.shape

((1156, 22, 23), (1156, 24), (267455, 6))

In [6]:
filtered_playerStats

array([[[1.00134900e+06, 3.00000000e+00, 3.00000000e+00, ...,
         8.00000000e+00, 0.00000000e+00, 2.58064516e-01],
        [1.00134900e+06, 3.00000000e+00, 3.00000000e+00, ...,
         2.00000000e+00, 0.00000000e+00, 6.66666667e-01],
        [1.00134900e+06, 3.00000000e+00, 3.00000000e+00, ...,
         3.00000000e+00, 0.00000000e+00, 4.28571429e-01],
        ...,
        [1.00134900e+06, 5.00000000e+00, 3.00000000e+00, ...,
         1.80000000e+01, 0.00000000e+00, 2.68656716e-01],
        [1.00134900e+06, 8.00000000e+00, 4.00000000e+00, ...,
         1.70000000e+01, 0.00000000e+00, 2.93103448e-01],
        [1.00134900e+06, 3.00000000e+00, 0.00000000e+00, ...,
         2.00000000e+00, 0.00000000e+00, 6.66666667e-01]],

       [[1.00135100e+06, 3.00000000e+00, 3.00000000e+00, ...,
         2.00000000e+00, 0.00000000e+00, 6.66666667e-01],
        [1.00135100e+06, 3.00000000e+00, 3.00000000e+00, ...,
         8.00000000e+00, 0.00000000e+00, 2.58064516e-01],
        [1.00135100e+06, 

In [20]:
# Save filtered datasets
filtered_team12Stats.write_csv('../finalDataSets/team12Stats.csv')
filtered_balltoball.write_csv('../finalDataSets/balltoball.csv')
np.save('../finalDataSets/playerStats.npy', filtered_playerStats)